### ISSUE TITLE
Cron updates?

### ISSUE THREAD

**Issue by otamate** [flancer32/mage2_ext_free_rates#1]
I installed this successfully, and imported currencies from the admin panel. I set it to be the enabled one for the cron import, once per day just after midnight but none came in. The log at var/log/system.log doesn't show any reference to the currency import. When I run the cron manually, the currencies aren't imported either. Isn't there some extra xml file needed to support these cron jobs?

[Update] This useful? : https://www.atwix.com/magento-2/setting-up-cron-jobs/

**Comment by flancer64** [comment]
Hi, @otamate .

I've added logging to the import code. Install `master` branch: 
```
$ composer require flancer32/mage2_ext_free_rates:"dev-master as 0.1.1"
```

Then you should get smth. like this:
```
$ cat  ./var/log/system.log | grep "Currency rates"
[2018-06-30 11:30:59] main.INFO: Currency rates request: https://free.currencyconverterapi.com/api/v3/convert?q=GBP_CNY [] []
```

when import is called.

I never used scheduled  currencies import before but magento cron is very capricious feature. First of all try to run twice mage cron manually:
```
$ ./bin/magento cron:run
```

Check system log for import messages. If there are no messages then check table `cron_schedule` for `currency_rates_update` job.

If there is no such job in `cron_schedule` try to debug  `\Magento\Directory\Model\Observer::scheduledUpdateCurrencyRates`

**Comment by otamate** [comment]
I think this will turn out to be easy. The docs to activate a custom module from cron are here: https://devdocs.magento.com/guides/v2.2/config-guide/cron/custom-cron-ref.html

All it boils down to is adding a file called crontab.xml to /etc similar to:
```
<config>
    <group id="currency_group">
        <job name="free_currency_import" instance="<classpath>" method="<method>">
            <schedule>* * * * *</schedule>
        </job>
    </group>
</config>
```

So all that's needed is the classpath of the import and the method (Alex?).

You can also optionally add one called cron_groups.xml. This creates a page which can be managed in the Magento admin panel. This will allow you to run the currency importer specifically, rather that with all the others. You use bin/magento cron:run --group="currency_group" when it's set up.

```
<?xml version="1.0"?>
<!--
/**
 * path:
 * magento_home/app/code/vendor/module/etc/cron_groups.xml
 */
-->
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:module:Magento_Cron:etc/cron_groups.xsd">
    <group id="currency_group">
        <schedule_generate_every>1</schedule_generate_every>
        <schedule_ahead_for>4</schedule_ahead_for>
        <schedule_lifetime>2</schedule_lifetime>
        <history_cleanup_every>10</history_cleanup_every>
        <history_success_lifetime>60</history_success_lifetime>
        <history_failure_lifetime>600</history_failure_lifetime>
        <use_separate_process>1</use_separate_process>
    </group>
</config>
```

**Comment by flancer64** [comment]
Sorry, I was too busy. 

As I see, rate updates should not be scheduled separately - just enable updates in admin. I think you need to [run Magento cron](https://devdocs.magento.com/guides/v2.0/config-guide/cli/config-cli-subcommands-cron.html) using linux cron:
```
* * * * * <path to php binary> <magento install dir>/bin/magento cron:run | grep -v "Ran jobs by schedule" >> <magento install dir>/var/log/magento.cron.log
```

**Comment by otamate** [comment]
Wait ... whether its scheduled by it's own cron group or as you say, by the main default scheduler you still need an /etc/crontab.xml to bind them or nothing happens. And in that file, you need the class and entry point of the method to call to perform the import.

**Comment by flancer64** [comment]
As I see:
* \Magento\Directory\Model\Currency\Import\AbstractImport::fetchRates
* \Magento\Directory\Model\Observer::scheduledUpdateCurrencyRates
* ./vendor/magento/module-directory/etc/crontab.xml
```
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:module:Magento_Cron:etc/crontab.xsd">
    <group id="default">
        <job name="currency_rates_update" instance="Magento\Directory\Model\Observer" method="scheduledUpdateCurrencyRates" />
    </group>
</config>
```

There is crontab job in `Magento_Directory` module already. 

Schedule for the job should be configured in `\Magento\Directory\Model\Observer::CRON_STRING_PATH`: 'crontab/default/jobs/currency_rates_update/schedule/cron_expr'

I suppose it is here:
![image](https://user-images.githubusercontent.com/5052385/42747932-eed6ed84-88e6-11e8-8b14-6b93828f3f5e.png)
