### ISSUE TITLE
since a few days, currency rates didnt working

### ISSUE THREAD

**Issue by dkostelyanets** [flancer32/mage2_ext_free_rates#3]
this code in fcc.php didnt working anymore:
`const CURRENCY_CONVERTER_URL = 'https://free.currencyconverterapi.com/api/v3/convert?q={{CURRENCY_FROM}}_{{CURRENCY_TO}}';`
cause in a few days ago author of currency converter changed api requests to his service.
now every free user should obtain his own api key for the service usage.
correct code, after getting api key is `const CURRENCY_CONVERTER_URL ='https://free.currencyconverterapi.com/api/v3/convert?apiKey=YourApiCodeGoesHere&q={{CURRENCY_FROM}}_{{CURRENCY_TO}}';`
and thank you much for your module. it's helps a lot!

**Comment by flancer64** [comment]
I've added API Key to module's config. Please, try version 0.2.0.
